// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	io "io"
	http "net/http"

	ksef "github.com/oskar1233/ksef/internal"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// AuthStatus provides a mock function with given fields: referenceNumber, authenticationToken
func (_m *API) AuthStatus(referenceNumber string, authenticationToken string) (*ksef.AuthenticationOperationStatusResponse, error) {
	ret := _m.Called(referenceNumber, authenticationToken)

	if len(ret) == 0 {
		panic("no return value specified for AuthStatus")
	}

	var r0 *ksef.AuthenticationOperationStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*ksef.AuthenticationOperationStatusResponse, error)); ok {
		return rf(referenceNumber, authenticationToken)
	}
	if rf, ok := ret.Get(0).(func(string, string) *ksef.AuthenticationOperationStatusResponse); ok {
		r0 = rf(referenceNumber, authenticationToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.AuthenticationOperationStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(referenceNumber, authenticationToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthTokenRedeem provides a mock function with given fields: authenticationToken
func (_m *API) AuthTokenRedeem(authenticationToken string) (*ksef.AuthenticationTokensResponse, error) {
	ret := _m.Called(authenticationToken)

	if len(ret) == 0 {
		panic("no return value specified for AuthTokenRedeem")
	}

	var r0 *ksef.AuthenticationTokensResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*ksef.AuthenticationTokensResponse, error)); ok {
		return rf(authenticationToken)
	}
	if rf, ok := ret.Get(0).(func(string) *ksef.AuthenticationTokensResponse); ok {
		r0 = rf(authenticationToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.AuthenticationTokensResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(authenticationToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticateWithKSeFToken provides a mock function with given fields: request
func (_m *API) AuthenticateWithKSeFToken(request ksef.InitTokenAuthenticationRequest) (*ksef.AuthenticationInitResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateWithKSeFToken")
	}

	var r0 *ksef.AuthenticationInitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(ksef.InitTokenAuthenticationRequest) (*ksef.AuthenticationInitResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(ksef.InitTokenAuthenticationRequest) *ksef.AuthenticationInitResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.AuthenticationInitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(ksef.InitTokenAuthenticationRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Authorize provides a mock function with given fields: signedXML, verifyCertificateChain
func (_m *API) Authorize(signedXML io.Reader, verifyCertificateChain bool) (*ksef.AuthenticationInitResponse, error) {
	ret := _m.Called(signedXML, verifyCertificateChain)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 *ksef.AuthenticationInitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader, bool) (*ksef.AuthenticationInitResponse, error)); ok {
		return rf(signedXML, verifyCertificateChain)
	}
	if rf, ok := ret.Get(0).(func(io.Reader, bool) *ksef.AuthenticationInitResponse); ok {
		r0 = rf(signedXML, verifyCertificateChain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.AuthenticationInitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader, bool) error); ok {
		r1 = rf(signedXML, verifyCertificateChain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Challenge provides a mock function with no fields
func (_m *API) Challenge() (*ksef.ChallengeResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Challenge")
	}

	var r0 *ksef.ChallengeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*ksef.ChallengeResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *ksef.ChallengeResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.ChallengeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DownloadInvoice provides a mock function with given fields: accessToken, ksefNumber
func (_m *API) DownloadInvoice(accessToken string, ksefNumber string) ([]byte, http.Header, error) {
	ret := _m.Called(accessToken, ksefNumber)

	if len(ret) == 0 {
		panic("no return value specified for DownloadInvoice")
	}

	var r0 []byte
	var r1 http.Header
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, http.Header, error)); ok {
		return rf(accessToken, ksefNumber)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(accessToken, ksefNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) http.Header); ok {
		r1 = rf(accessToken, ksefNumber)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(http.Header)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(accessToken, ksefNumber)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GenerateToken provides a mock function with given fields: accessToken, request
func (_m *API) GenerateToken(accessToken string, request ksef.GenerateTokenRequest) (*ksef.GenerateTokenResponse, error) {
	ret := _m.Called(accessToken, request)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 *ksef.GenerateTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ksef.GenerateTokenRequest) (*ksef.GenerateTokenResponse, error)); ok {
		return rf(accessToken, request)
	}
	if rf, ok := ret.Get(0).(func(string, ksef.GenerateTokenRequest) *ksef.GenerateTokenResponse); ok {
		r0 = rf(accessToken, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.GenerateTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ksef.GenerateTokenRequest) error); ok {
		r1 = rf(accessToken, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicKeyCertificates provides a mock function with no fields
func (_m *API) GetPublicKeyCertificates() ([]ksef.PublicKeyCertificate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKeyCertificates")
	}

	var r0 []ksef.PublicKeyCertificate
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]ksef.PublicKeyCertificate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []ksef.PublicKeyCertificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ksef.PublicKeyCertificate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenStatus provides a mock function with given fields: accessToken, referenceNumber
func (_m *API) GetTokenStatus(accessToken string, referenceNumber string) (*ksef.TokenStatusResponse, error) {
	ret := _m.Called(accessToken, referenceNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenStatus")
	}

	var r0 *ksef.TokenStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*ksef.TokenStatusResponse, error)); ok {
		return rf(accessToken, referenceNumber)
	}
	if rf, ok := ret.Get(0).(func(string, string) *ksef.TokenStatusResponse); ok {
		r0 = rf(accessToken, referenceNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.TokenStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(accessToken, referenceNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryInvoicesMetadata provides a mock function with given fields: accessToken, filters, sortOrder, pageOffset, pageSize
func (_m *API) QueryInvoicesMetadata(accessToken string, filters ksef.InvoiceQueryFilters, sortOrder string, pageOffset int, pageSize int) (*ksef.QueryInvoicesMetadataResponse, error) {
	ret := _m.Called(accessToken, filters, sortOrder, pageOffset, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for QueryInvoicesMetadata")
	}

	var r0 *ksef.QueryInvoicesMetadataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ksef.InvoiceQueryFilters, string, int, int) (*ksef.QueryInvoicesMetadataResponse, error)); ok {
		return rf(accessToken, filters, sortOrder, pageOffset, pageSize)
	}
	if rf, ok := ret.Get(0).(func(string, ksef.InvoiceQueryFilters, string, int, int) *ksef.QueryInvoicesMetadataResponse); ok {
		r0 = rf(accessToken, filters, sortOrder, pageOffset, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.QueryInvoicesMetadataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ksef.InvoiceQueryFilters, string, int, int) error); ok {
		r1 = rf(accessToken, filters, sortOrder, pageOffset, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshAccessToken provides a mock function with given fields: refreshToken
func (_m *API) RefreshAccessToken(refreshToken string) (*ksef.AuthenticationTokenRefreshResponse, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 *ksef.AuthenticationTokenRefreshResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*ksef.AuthenticationTokenRefreshResponse, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) *ksef.AuthenticationTokenRefreshResponse); ok {
		r0 = rf(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ksef.AuthenticationTokenRefreshResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
